### ISSUE TITLE
定期メッセージや更新内容などを配信する機能を追加する

### ISSUE THREAD

**Issue by jetyum** [koshianpan/Popopo#25]
## 概要
サーバーを利用するクライアントに対して通知を行いたい場合の手段の提供が必要だと考えたため.

**Comment by jetyum** [comment]
## 仕様
まず，ログインメッセージや死亡メッセージを変更する機能ではない．(それらを実装するとしたら日本語化機能を実装するときになる．)
`News`と`Info`の2種類を考える．
**News**  
ニュースのようなもの．新しい数件が常に表示される．
昔のものを見たい場合はメッセージをクリックして遡る．
通常ログイン時にそのプレーヤーに向けて送られる．
**Info**  
定期的に流れるメッセージ．プレイヤーへの注意や
軽い情報を流すときに用いる．
## ymlの構造
``` yml
news:
  number: 4
  articles:
    - "Hello! It's a big news!!"
info:
  period: 100
  articles:
    - "Hello! It's information!"
```
